---
version: "2.4"
services:
  mongodb1:
    image: 'penguintech/mongodbcluster'
    build: .
    ports:
      - "27017:27017"
    networks:
      - mongodbcluster
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  mongodbcluster: