---
version: "2.4"
services:
  mongodb1:
    image: 'penguintech/mongodbcluster'
    build: .
    ports:
      - "27017:27017"
    volumes:
     - shared-data:/etc/mongo
    networks:
      - mongodbcluster
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

  mongodb2:
    image: 'penguintech/mongodbcluster'
    build: .
    ports:
      - "27018:27017"
    volumes:
     - shared-data:/etc/mongo
    networks:
      - mongodbcluster
    environment:
      - PRIMARY_CLUSTER=0
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  shared-data:

networks:
  mongodbcluster: