---
- name: Start mongodb
  shell: mongod &

- name: Create admin user
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongodb.admin_username }}"
    password: "{{ mongodb.admin_password }}"
    roles: userAdminAnyDatabase
    state: present

- name: Connect and shutdown mongodb
  shell:
    cmd: |
      mongosh --port 27017 <<EOF
      use admin
      db.shutdownServer()
      EOF

- name: Generate MongoDB keyfile
  ansible.builtin.shell: openssl rand -base64 756 > /opt/mongodb/mongo.key
  args:
    creates: /opt/mongodb/mongo.key


- name: Template the config file
  template:
    src: templates/mongod_conf.j2
    dest: /opt/mongodb/mongod.conf